export const testimonialsMockData = [
  {
    id: '1',
    firstName: 'Elena',
    lastName: 'Ramirez',
    rating: 4,
    comment: 'Muy buena atención y el lugar es excelente.',
  },
  {
    id: '2',
    firstName: 'Laura',
    lastName: 'Fernandez',
    rating: 4,
    comment: 'Todo fue perfecto, superaron mis expectativas.',
  },
  {
    id: '3',
    firstName: 'Isabel',
    lastName: 'Martinez',
    rating: 4,
    comment: 'La calidad de servicio es insuperable.',
  },
  {
    id: '4',
    firstName: 'Carlos',
    lastName: 'Diaz',
    rating: 5,
    comment: 'Un lugar de confianza, siempre vuelvo.',
  },
  {
    id: '5',
    firstName: 'Elena',
    lastName: 'García',
    rating: 4,
    comment: 'Muy buena atención y el lugar es excelente.',
  },
  {
    id: '6',
    firstName: 'Maria',
    lastName: 'Lopez',
    rating: 5,
    comment: 'Me sentí muy cómodo, sin duda volveré.',
  },
  {
    id: '7',
    firstName: 'Ana',
    lastName: 'Fernandez',
    rating: 4,
    comment: 'La calidad de servicio es insuperable.',
  },
  {
    id: '8',
    firstName: 'Pedro',
    lastName: 'Gomez',
    rating: 4,
    comment: 'Muy buena experiencia, el ambiente es muy agradable.',
  },
  {
    id: '9',
    firstName: 'Ana',
    lastName: 'Diaz',
    rating: 4,
    comment: 'Me sentí muy cómodo, sin duda volveré.',
  },
  {
    id: '10',
    firstName: 'David',
    lastName: 'Diaz',
    rating: 5,
    comment: 'Me sentí muy cómodo, sin duda volveré.',
  },
  {
    id: '11',
    firstName: 'Maria',
    lastName: 'Perez',
    rating: 4,
    comment: 'Me sentí muy cómodo, sin duda volveré.',
  },
  {
    id: '12',
    firstName: 'Juan',
    lastName: 'García',
    rating: 4,
    comment: 'Muy buena experiencia, el ambiente es muy agradable.',
  },
  {
    id: '13',
    firstName: 'Ana',
    lastName: 'Lopez',
    rating: 4,
    comment: 'Recomiendo 100%, el trato fue muy profesional.',
  },
  {
    id: '14',
    firstName: 'Elena',
    lastName: 'Perez',
    rating: 4,
    comment: 'Me sentí muy cómodo, sin duda volveré.',
  },
  {
    id: '15',
    firstName: 'Laura',
    lastName: 'Sanchez',
    rating: 4,
    comment: 'Recomiendo 100%, el trato fue muy profesional.',
  },
];
