import spine from '../../../assets/images/services/backbone.png';
import knee from '../../../assets/images/services/knee.png';
import hip from '../../../assets/images/services/cadera.png';
import shoulder from '../../../assets/images/services/shoulder.png';
import footAndHand1 from '../../../assets/images/services/foot-and-hand-3.png';
import rehabilitation from '../../../assets/images/services/rehabilitation.png';
import circulation from '../../../assets/images/services/circulation1.png';
import sports from '../../../assets/images/services/sports.png';

export const allClinicServices = [
  {
    serviceId: 'spine',
    title: 'Columna Vertebral',
    shortDescription:
      'Atención especializada para el tratamiento de afecciones de la columna como protrusiones discales, hernias y escoliosis.',
    description: `Ofrecemos servicios de rehabilitación para condiciones como protrusiones discales, hernias, espondilolistesis, radiculopatías, ciática, escoliosis, rectificación, hiperlordosis y procedimientos quirúrgicos de columna.`,
    alt: 'Columna Vertebral',
    image: spine,
    isPrimary: true,
    conditionsTreated: [
      'Protrusiones discales',
      'Hernias',
      'Espondilolistesis',
      'Radiculopatías',
      'Ciática',
      'Escoliosis',
      'Rectificación',
      'Hiperlordosis',
      'Procedimientos quirúrgicos de columna',
    ],
    treatmentApproaches: [
      'Planes de rehabilitación personalizados',
      'Técnicas avanzadas de manejo del dolor',
      'Ejercicios de corrección postural',
      'Terapias de alineación espinal',
    ],
  },
  {
    serviceId: 'knee',
    title: 'Rodilla',
    shortDescription:
      'Tratamientos integrales para problemas de rodilla como lesiones de menisco, artritis y esguinces de ligamentos.',
    description: `Ofrecemos tratamientos para condiciones de rodilla como lesiones de menisco, desgaste, artritis, condromalacia, esguinces de ligamentos, quistes de Baker, derrame articular, tejido fibroso, procedimientos quirúrgicos de rodilla y fracturas.`,
    alt: 'Rodilla',
    image: knee,
    isPrimary: true,
    conditionsTreated: [
      'Lesiones de menisco',
      'Desgaste',
      'Artritis',
      'Condromalacia',
      'Esguinces de ligamentos',
      'Quistes de Baker',
      'Derrame articular',
      'Tejido fibroso',
      'Procedimientos quirúrgicos de rodilla',
      'Fracturas',
    ],
    treatmentApproaches: [
      'Ejercicios de fortalecimiento',
      'Técnicas de movilización articular',
      'Terapias para alivio del dolor',
      'Soportes y férulas para rodilla',
    ],
  },
  {
    serviceId: 'hip',
    title: 'Cadera',
    shortDescription: 'Soluciones efectivas para fracturas de cadera, bursitis y cambios mecánicos articulares.',
    description: `Nuestros servicios incluyen tratamientos para fracturas de cadera, bursitis, desgaste y cambios mecánicos articulares.`,
    alt: 'Cadera',
    image: hip,
    isPrimary: true,
    conditionsTreated: ['Fracturas de cadera', 'Bursitis', 'Desgaste', 'Cambios mecánicos articulares'],
    treatmentApproaches: [
      'Ejercicios específicos de fortalecimiento',
      'Sesiones de terapia manual',
      'Modalidades para alivio del dolor',
      'Técnicas de estabilización articular de cadera',
    ],
  },
  {
    serviceId: 'shoulder',
    title: 'Hombro',
    shortDescription:
      'Atención experta para lesiones de hombro como problemas del manguito rotador, tendinitis y desgarros.',
    description: `Proveemos tratamientos para condiciones de hombro como fracturas, bursitis, desgaste, cambios mecánicos articulares, problemas del manguito rotador, tendinitis y desgarros.`,
    alt: 'Hombro',
    image: shoulder,
    isPrimary: true,
    conditionsTreated: [
      'Fracturas',
      'Bursitis',
      'Desgaste',
      'Cambios mecánicos articulares',
      'Problemas del manguito rotador',
      'Tendinitis',
      'Desgarros',
    ],
    treatmentApproaches: [
      'Ejercicios terapéuticos',
      'Movilización de tejidos blandos',
      'Fortalecimiento del manguito rotador',
      'Estabilización articular del hombro',
    ],
  },
  {
    serviceId: 'foot-and-hand',
    title: 'Pie y Mano',
    shortDescription: 'Programas de rehabilitación para fracturas, tendinitis y síndrome del túnel carpiano.',
    description: `Nuestros servicios de rehabilitación abordan condiciones como fracturas, tendinitis, tejido fibroso, esguinces, espolones calcáneos, fascitis plantar, síndrome del túnel carpiano, tendinitis de De Quervain y radiculopatías.`,
    alt: 'Pie y Mano',
    image: footAndHand1,
    isPrimary: true,
    conditionsTreated: [
      'Fracturas',
      'Tendinitis',
      'Tejido fibroso',
      'Esguinces',
      'Espolones calcáneos',
      'Fascitis plantar',
      'Síndrome del túnel carpiano',
      'Tendinitis de De Quervain',
      'Radiculopatías',
    ],
    treatmentApproaches: [
      'Férulas personalizadas',
      'Ejercicios terapéuticos para manos',
      'Ajustes ergonómicos',
      'Terapia de tejidos blandos',
    ],
  },
  {
    serviceId: 'rehabilitation',
    title: 'Rehabilitación',
    shortDescription: 'Terapia física especializada para condiciones post-cardiacas y cirugías.',
    description: `Ofrecemos programas y seguimiento para condiciones post-cardiacas, pacientes con marcapasos, cirugías a corazón abierto y condiciones cardio-pulmonares.`,
    alt: 'Rehabilitación',
    image: rehabilitation,
    isPrimary: true,
    conditionsTreated: [
      'Condiciones post-cardiacas',
      'Marcapasos',
      'Cirugías a corazón abierto',
      'Condiciones cardio-pulmonares',
    ],
    treatmentApproaches: [
      'Ejercicios físicos monitoreados',
      'Acondicionamiento cardio-pulmonar',
      'Planes de progresión gradual',
      'Protocolos de recuperación post-cirugía',
    ],
  },
  {
    serviceId: 'circulation',
    title: 'Circulación',
    shortDescription: 'Tratamiento para problemas circulatorios como várices y úlceras.',
    description: `Nuestros servicios incluyen tratamientos para problemas circulatorios como várices, linfedema, problemas de circulación y úlceras.`,
    alt: 'Circulación',
    image: circulation,
    isPrimary: true,
    conditionsTreated: ['Várices', 'Linfedema', 'Problemas de circulación', 'Úlceras'],
    treatmentApproaches: [
      'Terapia de compresión',
      'Drenaje linfático manual',
      'Planes de modificación de estilo de vida',
      'Monitoreo de salud vascular',
    ],
  },
  {
    serviceId: 'sports',
    title: 'Deportes',
    shortDescription: 'Rehabilitación deportiva incluyendo corrección postural y recuperación muscular.',
    description: `Proveemos servicios de rehabilitación deportiva como masajes de recuperación muscular, corrección postural, readaptación deportiva, crioterapia y orientación en la prescripción de calzado deportivo.`,
    alt: 'Deportes',
    image: sports,
    isPrimary: true,
    conditionsTreated: [
      'Recuperación muscular',
      'Corrección postural',
      'Readaptación deportiva',
      'Crioterapia',
      'Prescripción de calzado deportivo',
    ],
    treatmentApproaches: [
      'Masajes de recuperación muscular',
      'Evaluaciones biomecánicas',
      'Planes de entrenamiento personalizados',
      'Sesiones de crioterapia',
    ],
  },
];
